![](../static/cran.png)

## Matrices
A Matrix is a two-dimensional collection of data. It is a fundamental object for linear algebra

In [9]:
# Matrices can be created in a variety of ways
# put the columns together cbind():
c1 <- c(1,2,3)
c2 <- c(4,5,6)
m <- cbind(c1, c2)
m

c1 c2
[1,]  1  4
[2,]  2  5
[3,]  3  6

In [4]:
# putting the rows together rbind()
m2 <- rbind(c1, c2)
m2

[,1] [,2] [,3]
c1    1    2    3
c2    4    5    6

In [13]:
# Matrix dimensions
# We may use nrow(), ncol(), dim() returns the number of rows, number of columns and dimension of a matrix respectively
nrow(m)
ncol(m)
dim(m)

[1] 3

[1] 2

[1] 3 2

In [7]:
# We may bind not only rows or columns, in general we can bind columns
rbind(m2, m2)
# Matrices show be "compatible" for the bind operation, 
# that is: rbind(m1,m2)=>ncol(m1)==ncol(m2)
# also cbind(m1,m2)=>nrow(m1)==nrow(m2)

[,1] [,2] [,3]
c1    1    2    3
c2    4    5    6
c1    1    2    3
c2    4    5    6

In [23]:
# We may also create matrix by: specifying a vector and the number of rows
m3 <- matrix(c(1,2,3,4,5,6,7,8,9,10,11,12), nrow=3)
m3

[,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

In [18]:
# Similarly, specifying a vector and the number of columns
m4 <- matrix(c(1,2,3,4,5,6,7,8,9,10,11,12), ncol=6)
m4

[,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    3    5    7    9   11
[2,]    2    4    6    8   10   12

In [19]:
# Please, notice how the previous matrices were create: "by column"
# We may create the matrix "by row" as follows:
m5 <- matrix(c(1,2,3,4,5,6,7,8,9,10,11,12), ncol=6, byrow=T)
m5

[,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    2    3    4    5    6
[2,]    7    8    9   10   11   12

In [7]:
# In general the matrix function: matrix(vector,nrow,rcol,byrow)
matrix(c(1,2,3,4,5),nrow=2,ncol=2,byrow=T)
matrix(c(1,2,3,4,5),nrow=2,ncol=4,byrow=T)

Warning message in matrix(c(1, 2, 3, 4, 5), nrow = 2, ncol = 2, byrow = T):
“data length [5] is not a sub-multiple or multiple of the number of rows [2]”

[,1] [,2]
[1,]    1    2
[2,]    3    4

Warning message in matrix(c(1, 2, 3, 4, 5), nrow = 2, ncol = 4, byrow = T):
“data length [5] is not a sub-multiple or multiple of the number of rows [2]”

[,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    1    2    3

In [10]:
# Operations on Matrices: Transpose t()
t(m)

[,1] [,2] [,3]
c1    1    2    3
c2    4    5    6

In [17]:
# Sum and product (scalar and vectorial)
2*m + 1 
m * m
t(m) %*% m

c1 c2
[1,]  3  9
[2,]  5 11
[3,]  7 13

c1 c2
[1,]  1 16
[2,]  4 25
[3,]  9 36

c1 c2
c1 14 32
c2 32 77

In [ ]:
# Retrieving elements and sub-matrices
m[1,1]
m[,2]
m3[2,2:3]

In [41]:
# Matrix inverse and determinant: solve() and det()
m1 <- cbind(c(1,2), c(2,3))
solve(m1)
det(m1)

[,1] [,2]
[1,]   -3    2
[2,]    2   -1

[1] -1

In [42]:
# Matrix deconstruction c()
c(m)

[1] 1 1 2 2

In [48]:
# Solving a system of linear equations
cx <- c(1,2,3)
cy <- c(1,1,2)
cz <- c(1,1,3)
y <- c(1,2,5)
m <-cbind(cx,cy,cz)

# Names to rows and columms
dimnames(m) = list(c("r1", "r2", "r3"), c("x", "y", "z"))
m

x y z
r1 1 1 1
r2 2 1 1
r3 3 2 3

In [49]:
# Solution Ax=Y => x = CY where C is inverse of A (if A is non-singular)
# Therefore x = Solve(A) %*% Y
# If matrix is not square to use: solve(t(m)%*%m) %*% t(m)
solve(m) %*% y

[,1]
x    1
y   -2
z    2